name: 'Yarn Build'
description: 'Github Action for performing Yarn build'
author: 'Damian Sloane <damian.sloane@eonx.com>'
inputs:
  path:
    description: 'Path to the package to be deployed relative to the repository root'
    required: false
    default: ""
  environment:
    description: 'Environment code, this should be lowercase/hyphenated (e.g. "dev", "staging", "prod")'
    required: true
  npm_token:
    description: 'GitHub packages access token'
    default: ""
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
